import sys

RESOURCE_RANGE = 100
STARTING_POSITION = (0, 0)
TERMINATION_VARIANCE = 200  # TODO: find optimal value
MIN_GENERATION = 200  # TODO: find optimal value
MAX_GENERATION = 1000  # TODO: find optimal value
IMAGE_NAME = sys.argv[1]

COGNITIVE_RATE = 0.25
SOCIAL_RATE = 0.25
INERTIA_RATE = 2
MAXIMUM_VELOCITY = 20

POPULATION_SIZE = 2
