RESOURCE_RANGE = 100
STARTING_POSITION = (0, 0)
POPULATION_SIZE = 2
TERMINATION_VARIANCE = 5000  # TODO: find optimal value
MIN_GENERATION = 100  # TODO: find optimal value
MAX_GENERATION = 20  # TODO: find optimal value
